### ISSUE TITLE
How to run this on Windows

### ISSUE THREAD

**Issue by Pastew** [StephenSorriaux/mangosone-docker#14]
Hello,

is it possible to run it on Windows? 
If so - where to put maps and how modify **docker-compose.yml** to use provided maps?
```
       - mangos_maps:/etc/mangos/maps
       - mangos_vmaps:/etc/mangos/vmaps
       - mangos_mmaps:/etc/mangos/mmaps
       - mangos_dbc:/etc/mangos/dbc
```

**Comment by StephenSorriaux** [comment]
Hi,

Which version of Windows are you using? If you are using Docker on Windows in Linux container mode, it should be fine.

Concerning the maps, you have two ways to specify their location:

1.  Replace `mangos_maps`, `mangos_vmaps`, `mangos_mmaps` and `mangos_dbc` with their path on your host (for instance, the line `- mangos_maps:/etc/mangos/maps` becomes `- c:/wow/mymaps/maps:/etc/mangos/maps`)

2. Update the volumes' configuration at the bottom of the docker-compose file,
```yml
volumes:
    db_data:
    mangos_maps:
```
becomes
```yml
volumes:
  db_data:
  mangos_maps:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: c:/wow/mymaps/maps
```
